Traceback (most recent call last):
  File "/Users/winniecook/Documents/Updating_Projects/Script_Projects/forest-fire-analysis/scripts/01_data_preprocessing.py", line 53, in <module>
    main(input_file, output_file)
  File "/Users/winniecook/Documents/Updating_Projects/Script_Projects/forest-fire-analysis/scripts/01_data_preprocessing.py", line 45, in main
    df = normalize_features(df)
         ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/winniecook/Documents/Updating_Projects/Script_Projects/forest-fire-analysis/scripts/01_data_preprocessing.py", line 31, in normalize_features
    df[numeric_features] = scaler.fit_transform(df[numeric_features])
                                                ~~^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/pandas/core/frame.py", line 4108, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 6200, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "/opt/anaconda3/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 6252, in _raise_if_missing
    raise KeyError(f"{not_found} not in index")
KeyError: "['DMC', 'DC'] not in index"
